import glob

####
# import the environment and set up a unique sub-environment
####
Import('env variant_dir pluginTargets')

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)
if env["OS"] == "windows":
   objs = objs + pluginTargets

####
# build the library and set up an alias to ease building it later
####
lib = env.SharedLibrary("%s/SimpleApiLib" % variant_dir,objs)
env.Alias('libSimpleApiLib', lib)

####
# return the library
####
Return('lib')
