import glob

####
# import the environment
####
Import('env variant_dir TOOLPATH')
env = env.Clone()
env.Tool("ehs",toolpath=[TOOLPATH])
env.Tool("minizip",toolpath=[TOOLPATH])
env.Tool("zip",toolpath=[TOOLPATH])
if env["OS"] == "windows":
   env.Tool("zlib", toolpath=[TOOLPATH])

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/Kml' % variant_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('Kml', libInstall)

####
# return the plug-in library
####
Return("libInstall")
