import glob

####
# import the environment
####
Import('env variant_dir TOOLPATH')
env = env.Clone()
env.Tool('opencv', toolpath=[TOOLPATH])

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to ease building it later
####
lib = env.SharedLibrary('%s/ObjectFinding' % variant_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('ObjectFinding', libInstall)

####
# return the plug-in library
####
Return("libInstall")
