# Install script for directory: C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim/apps

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/ossim")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-adrg-dump/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-applanix2ogeom/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-autreg/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-band-merge/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-btoa/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-chgkwval/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-chipper/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-cli/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-cmm/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-computeSrtmStats/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-correl/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-create-bitmask/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-create-cg/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-create-histo/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-deg2dms/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-dms2deg/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-dump-ocg/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-envi-cg/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-equation/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-extract-vertices/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-header-crawl/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-icp/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-igen/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-image-compare/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-image-synth/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-img2md/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-img2rr/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-info/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-modopt/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-mosaic/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-ogeom2ogeom/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-orthoigen/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-pc2dem/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-pixelflip/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-plot-histo/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-preproc/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-project-point/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-prune/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-rejout/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-rpcgen/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-rpf/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-senint/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-space-imaging/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-src2src/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-swapbytes/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-tfw2ogeom/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-tool-client/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-tool-server/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-viirs-proc/cmake_install.cmake")
  include("C:/dev/opticks-org/opticks/Dependencies/src/ossim/ossim-build/apps/ossim-ws-cmp/cmake_install.cmake")

endif()

