# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - template: azure-devops/build-windows.yml
    parameters:
      name: 'Windows_VS2017_x64'
      targetPlatform: x64
      image: 'vs2017-win2016'
  - job: Windows_VS2017_x64
    pool:
      vmImage: 'windows-latest'
    steps:
      - script: git submodule update --init Dependencies\vcpkg
        displayName: Checkout vcpkg submodule
      - script: .\Dependencies\vcpkg\bootstrap-vcpkg.bat
        displayName: Bootstrap vcpkg
      - script: .\Dependencies\vcpkg\vcpkg.exe install @Dependencies\vcpkg.list --vcpkg-root Dependencies\vcpkg --triplet x64-windows
        displayName: install vcpkg dependencies
      - task: CMake@1
        inputs:
          cmakeArgs: '-A x64 -DCMAKE_TOOLCHAIN_FILE=../Dependencies/vcpkg/scripts/buildsystems/vcpkg.cmake ../Code/application'
      - task: MSBuild@1
        inputs:
          solution: 'build\ALL_BUILD.vcxproj'
          maximumCpuCount: true
          platform: 'x64'
