import glob

####
# import the environment
####
Import('env build_dir')

####
# subdirectories to build objects from
####
subdirs = ["Layer","Animation","Plot"]

####
# build top-level sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.Object(srcs)

####
# build subdirectory sources
####
for sub in subdirs:
   env.Append(CPPPATH="#/Desktop/%s" % sub)
   srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("%s/*.cpp" % sub))
   objs += env.Object(srcs)

####
# build the library and set up an alias to ease building it later
####
lib = env.Library("%s/Desktop" % build_dir,objs)
env.Alias('libDesktop', lib)

####
# return the library
####
Return('lib')
