import glob 
####
# import the environment
####
Import('env variant_dir libInstallTargets')

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), filter(lambda x: x != "ModuleShell.cpp", glob.glob("*.cpp")))
objs = env.Object(srcs)
ms_env = env.Clone() # compile to ModuleShell.os instead of so_ModuleShell.o
ms_env.Replace(SHOBJPREFIX = '', SHOBJSUFFIX = '.os')
module_shell = ms_env.SharedObject("%s/ModuleShell.cpp" % variant_dir)

####
# build the library and set up an alias to ease building it later
####
lib = env.Library("%s/PlugInLib" % variant_dir,objs)
libInstallTargets.append(lib)
libInstallTargets.append(module_shell)
env.Alias('libPlugInLib', [lib,module_shell])

Return('lib')
