find_path(OpenJpeg2_INCLUDE_DIR cio.h PATH_SUFFIXES openjpeg2 v3p/openjpeg2 vxl/v3p/openjpeg2)
message(STATUS "OpenJpeg2_INCLUDE_DIR: ${OpenJpeg2_INCLUDE_DIR}")
if(NOT OpenJpeg2_INCLUDE_DIR)
   message(STATUS "OpenJpeg2 header file cio.h not found. Did you install the vxl-devel package?") 
else()
   message(STATUS "OpenJpeg2_INCLUDE_DIR: ${OpenJpeg2_INCLUDE_DIR}")
   find_library(OpenJpeg2_LIBRARY_RELEASE NAMES openjpeg2)
   find_library(OpenJpeg2_LIBRARY_DEBUG NAMES openjpeg2d)

   include(SelectLibraryConfigurations)
   select_library_configurations(OpenJpeg2)

   set(OpenJpeg2_INCLUDE_DIRS ${OpenJpeg2_INCLUDE_DIR})
   mark_as_advanced(OpenJpeg2_INCLUDE_DIR)

   include(FindPackageHandleStandardArgs)
   find_package_handle_standard_args(OpenJpeg2 REQUIRED_VARS OpenJpeg2_INCLUDE_DIR OpenJpeg2_LIBRARY)
   set(OpenJpeg2_FOUND ${OPENJPEG2_FOUND})

   if(OpenJpeg_FOUND)
      message(STATUS "OpenJpeg2_LIBRARY: ${OpenJpeg2_LIBRARY}")
      file(STRINGS "${OpenJpeg2_INCLUDE_DIR}/cio.h" OpenJpeg2_opj_stream_seek REGEX "opj_stream_seek")
      file(STRINGS "${OpenJpeg2_INCLUDE_DIR}/cio.h" OpenJpeg2_opj_stream_read_skip REGEX "opj_stream_read_skip")
      if(OpenJpeg2_opj_stream_read_skip)
         include_directories(${OpenJpeg2_INCLUDE_DIR})
         add_definitions(-DHAVE_CIO_H=1)
      endif()
   endif()
endif()
