if (WIN32)
  if ("${CMAKE_GENERATOR}" MATCHES "Visual Studio")
    get_filename_component(kit_dir "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" REALPATH)
  endif ()

  file(GLOB_RECURSE temp "${kit_dir}/bin/MC.exe")
  foreach (fname ${temp})
    if (CMAKE_CL_64)
      if (${fname} MATCHES ".*/x64/mc.exe")
        get_filename_component(kit_bindir "${fname}" DIRECTORY)
        break()
      endif ()
    else ()
      if (${fname} MATCHES ".*/x86/mc.exe")
        get_filename_component(kit_bindir "${fname}" DIRECTORY)
        break()
      endif ()
    endif ()
  endforeach ()

  find_program(MessageCompiler_EXECUTABLE mc.exe HINTS "${kit_bindir}"
    DOC "path to Microsoft message compiler (mc.exe)")
  if (NOT MessageCompiler_EXECUTABLE)
    message(FATAL_ERROR "message compiler not found: required to build")
  endif (NOT MessageCompiler_EXECUTABLE)
  message(STATUS "Found message compiler: ${MessageCompiler_EXECUTABLE}")
  mark_as_advanced(MessageCompiler_EXECUTABLE)
endif(WIN32)
