import glob

####
# import the environment
####
Import('env variant_dir TOOLPATH')
env = env.Clone()
env.Tool("hdf5",toolpath=[TOOLPATH])
env.Prepend(CPPDEFINES=["APPLICATION_XERCES"], CPPPATH=["$COREDIR/HdfPlugInLib",variant_dir], LIBS=["HdfPlugInLib"])

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/Ice' % variant_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('Ice', libInstall)

####
# return the plug-in library
####
Return("libInstall")
