import os
import sys

####
# Set up the options and environment
####
vars = Variables()
vars.Add('CODEDIR', 'Code directory', '#/../../Code')
vars.Add('OPTICKSDEPENDENCIES', 'Dependencies directory')
vars.Add('BUILDDIR','Directory for build files','$CODEDIR/Build')
vars.Add('VERSION','Version string for the package. This includes the package version number. For example, 4.5.0-1','Unknown')
vars.Add('OUTPUT_DIR','Intermediate directory used to generate the install package.', '#/PackageOutput')

OPTICKS_PLATFORM = "unknown"
if sys.platform.startswith("linux"):
   OPTICKS_PLATFORM = "linux-x86_64"
else:
   raise EnvironmentError('Invalid or unknown platform')

TOOLPATH=Dir("#/../../Code/application/CompileSettings")
env = Environment(variables=vars,
                  ENV=os.environ,
                  tools=["default", "packaging"],
                  toolpath=[TOOLPATH])

BUILDDIR = env.Dir(env["BUILDDIR"]).abspath
env["BINDIR"] = '%s/Binaries-%s-release/Bin' % (BUILDDIR,OPTICKS_PLATFORM)
env["PLUGINDIR"] = '%s/Binaries-%s-release/PlugIns' % (BUILDDIR,OPTICKS_PLATFORM)
env["LIBDIR"] = '%s/Binaries-%s-release/Lib' % (BUILDDIR,OPTICKS_PLATFORM)


Help(vars.GenerateHelpText(env))

####
# Build the installation packages
####
if OPTICKS_PLATFORM == "linux-x86_64":
   import sys
   sys.path.append(TOOLPATH.abspath)
   sys.path.append(env.Dir('$CODEDIR').abspath)
   import commonutils
   rpmenv = env.Clone()
   rpmenv['PREF'] = '/opt/Opticks'
   rpmenv.Install('$PREF/Bin', rpmenv.File('#/linux_extra/Environment'))
   rpmenv.Install('$PREF/Bin', rpmenv.File('#/linux_extra/Opticks'))
   rpmenv.Install('$PREF/Bin', rpmenv.File('#/linux_extra/OpticksBatch'))
   rpmenv.Install('$PREF/Bin', rpmenv.File('$CODEDIR/application/Gui/res/application-large.png'))
   rpmenv.Install('$PREF/Bin', rpmenv.File('$BINDIR/linuxBatch'))
   rpmenv.Install('$PREF/Bin', rpmenv.File('$BINDIR/linuxOpticks'))
   for src,dst in commonutils.get_dependencies(rpmenv.Dir('$OPTICKSDEPENDENCIES').abspath, 'Linux', False, '64'):
       rpmenv.Install('$PREF/Bin/%s' % dst, rpmenv.File(src))
   rpmenv.Install('$PREF/Lib', rpmenv.File('$LIBDIR/libSimpleApiLib.so'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/1-ApplicationDefaults.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/2-ApplicationMode.cfg'))
   rpmenv.InstallAs(target='$PREF/DefaultSettings/3-ApplicationTempDir.cfg', source=rpmenv.File('#/linux_extra/3-ApplicationTempDir.cfg.in'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/40-PicturesExporters.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/41-MovieExporter.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/42-Nitf.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/43-IceExporter.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/44-AnnotationImagePalette.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/45-ConvolutionFilters.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/46-GeographicFeatures.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/50-KmlServer.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/55-Modis.cfg'))
   rpmenv.Install('$PREF/DefaultSettings', rpmenv.File('$CODEDIR/Release/DefaultSettings/60-SpatialResampler.cfg'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/AnnotationImagePalette.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Aspam.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/AutoImporter.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/BandBinning.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/BandMath.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/ConvolutionFilter.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/CoreIo.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Covariance.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/DataFusion.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Dted.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/ENVI.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Fits.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/GdalImporter.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Generic.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/GeographicFeatures.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/GeoMosaic.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Georeference.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Hdf.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Ice.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/ImageComparison.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Kml.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Las.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Modis.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/MovieExporter.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/NitfCommonTre.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Nitf.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/ObjectFinding.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Pca.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Pictures.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Results.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Scripts.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/SecondMoment.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/ShapeFileExporter.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Sio.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/SpatialResampler.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/Wavelength.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/WizardExecutor.so'))
   rpmenv.Install('$PREF/PlugIns', rpmenv.File('$PLUGINDIR/WizardItems.so'))
   rpmenv.Install('$PREF/SupportFiles/Annotation', rpmenv.File('$CODEDIR/Release/SupportFiles/Annotation/default.cgm'))
   rpmenv.Install('$PREF/SupportFiles/Annotation', rpmenv.File('$CODEDIR/Release/SupportFiles/Annotation/East.ano'))
   rpmenv.Install('$PREF/SupportFiles/Annotation', rpmenv.File('$CODEDIR/Release/SupportFiles/Annotation/North.ano'))
   rpmenv.Install('$PREF/SupportFiles/Cg', rpmenv.File('$CODEDIR/Release/SupportFiles/Cg/ByPass.cg'))
   rpmenv.Install('$PREF/SupportFiles/Cg', rpmenv.File('$CODEDIR/Release/SupportFiles/Cg/ColormapDisplay.cg'))
   rpmenv.Install('$PREF/SupportFiles/Cg', rpmenv.File('$CODEDIR/Release/SupportFiles/Cg/EdgeDetection.cg'))
   rpmenv.Install('$PREF/SupportFiles/Cg', rpmenv.File('$CODEDIR/Release/SupportFiles/Cg/GrayscaleDisplay.cg'))
   rpmenv.Install('$PREF/SupportFiles/Cg', rpmenv.File('$CODEDIR/Release/SupportFiles/Cg/RgbDisplay.cg'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/autocolor.clu'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/HotIronAlpha.clu'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/HotIron.clu'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/Primaries.clu'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/RedTemp.cgr'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/SpectrumAlpha.clu'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/Spectrum.cgr'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/StopLight.clu'))
   rpmenv.Install('$PREF/SupportFiles/ColorTables', rpmenv.File('$CODEDIR/Release/SupportFiles/ColorTables/WeatherMap.clu'))
   rpmenv.Install('$PREF/SupportFiles/ImageFilters', rpmenv.File('$CODEDIR/Release/SupportFiles/ImageFilters/FilterDefaults.gic'))
   rpmenv.Install('$PREF/SupportFiles/SecurityMarkings', rpmenv.File('$CODEDIR/Release/SupportFiles/SecurityMarkings/1-SecurityValues.sec'))
   rpmenv.Install('$PREF/SupportFiles/SecurityMarkings', rpmenv.File('$CODEDIR/Release/SupportFiles/SecurityMarkings/ClassificationLevels.txt'))
   rpmenv.Install('$PREF/SupportFiles/Xml', rpmenv.File('$CODEDIR/Release/SupportFiles/Xml/opticks-1.xsd'))
   rpmenv.Install('$PREF/SupportFiles/Xml', rpmenv.File('$CODEDIR/Release/SupportFiles/Xml/opticks-2.xsd'))
   rpmenv.Install('$PREF/SupportFiles/Xml', rpmenv.File('$CODEDIR/Release/SupportFiles/Xml/opticks-3.xsd'))
   rpmenv.Install('$PREF/Templates', rpmenv.File('$CODEDIR/Release/Templates/MultipleImages.spg'))
   rpmenv.Install('$PREF/Templates', rpmenv.File('$CODEDIR/Release/Templates/SingleImage.spg'))
   rpmenv.Install('$PREF/Templates', rpmenv.File('$CODEDIR/Release/Templates/ZoomedImages.spg'))
   rpmenv.Install('$PREF/Extensions/AutoInstall', rpmenv.File('#/linux_extra/.dummy'))

   # NOTE: The DESCRIPTION field is newline sensitive.
   # It must end in a newline but not contain other newlines. If you must have one see:
   # http://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Description
   pkg = rpmenv.Package(NAME='opticks',
                        VERSION=env['VERSION'],
                        PACKAGEVERSION=0,
                        LICENSE='LGPLv2',
                        PACKAGEROOT=env.Dir(env['OUTPUT_DIR']),
                        X_RPM_PREFIX='/opt/Opticks',
                        PACKAGETYPE='rpm',
                        X_RPM_GROUP='Applications/Scientific Visualization',
                        ARCHITECTURE='amd64',
                        SUMMARY='Opticks is a remote sensing P&E workbench.',
                        DESCRIPTION='''Opticks is an expandable remote sensing and imagery analysis software platform that is free and open source. If you've used other commercial tools like: ERDAS IMAGINE, RemoteView, ENVI, or SOCET GXP, then you need to give Opticks a try. Unlike other competing tools, you can add capability to Opticks by creating an extension. Opticks provides the most advanced extension capability of any remote sensing tool on the market.
''',
                        SOURCE_URL='https://opticks.org',
                       )
   env.Alias('rpm', pkg)
