import glob

####
# import the environment
####
Import('env variant_dir TOOLPATH')
env = env.Clone()
env.Tool("ossim",toolpath=[TOOLPATH])
env.Tool("openjpeg",toolpath=[TOOLPATH])
env.Prepend(CPPPATH=["$COREDIR/NitfPlugInLib"], LIBS=["NitfPlugInLib"])
if env["OS"] == "windows":
   env.AppendUnique(LINKFLAGS=["/FORCE:MULTIPLE", "/ignore:4006"])

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/Nitf' % variant_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('Nitf', libInstall)

####
# return the plug-in library
####
Return("libInstall")
