import glob

####
# import the environment
####
Import('env build_dir')

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.Object(srcs)

####
# return the objects
####
Return('objs')
import glob

####
# import the environment
####
Import('env variant_dir')

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.Object(srcs)

####
# return the objects
####
Return('objs')
