import glob

####
# import the environment
####
Import('env build_dir TOOLPATH')
env = env.Clone()
env.Tool("ffmpeg",toolpath=[TOOLPATH])
env.Append(CPPFLAGS="-DOFFSET_T_DEFINED")

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/MovieExporter' % build_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('MovieExporter', libInstall)

####
# return the plug-in library
####
Return("libInstall")
