import glob

####
# import the environment
####
Import('env build_dir')

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.Object(srcs)

####
# build the library and set up an alias to ease building it later
####
lib = env.Library("%s/PlugInManager" % build_dir,objs)
env.Alias('libPlugInManager', lib)

####
# return the library
####
Return('lib')
