import glob

####
# import the environment
####
Import('env variant_dir TOOLPATH')
env = env.Clone()
env.Tool('ossim', toolpath=[TOOLPATH])
env.Tool('opencv', toolpath=[TOOLPATH])

####
# build sources
####
env.Append(CPPPATH=[variant_dir])
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
srcs = env.Moc(env.Uic('%s/ConvolutionMatrixWidget.ui' % variant_dir)) + srcs
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/ConvolutionFilter' % variant_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('ConvolutionFilter', libInstall)

####
# return the plug-in library
####
Return("libInstall")
