import glob

####
# import the environment
####
Import('env extra_obj build_dir TOOLPATH')
env = env.Copy()
env.Tool('ossim', toolpath=[TOOLPATH])

####
# build sources
####
env.Append(CPPPATH=[build_dir])
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
srcs = env.Moc(env.Uic('%s/ConvolutionMatrixWidget.ui' % build_dir)) + srcs
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/ConvolutionFilter' % build_dir,objs+extra_obj)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('ConvolutionFilter', libInstall)

####
# return the plug-in library
####
Return("libInstall")
