import glob

####
# import the environment
####
Import('env build_dir TOOLPATH PLATFORM')
env = env.Clone(PLATFORM=PLATFORM)
env.Tool("ossim",toolpath=[TOOLPATH])
env.Tool("qwt",toolpath=[TOOLPATH])

####
# build sources
####
srcs = map(lambda x,bd=build_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/Pca' % build_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('Pca', libInstall)

####
# return the plug-in library
####
Return("libInstall")
