import glob

####
# import the environment
####
Import('env extra_obj variant_dir TOOLPATH')
env = env.Clone()
env.Tool('liblas',toolpath=[TOOLPATH])

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/Las' % variant_dir,objs+extra_obj)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('Las', libInstall)

####
# return the plug-in library
####
Return("libInstall")
