import glob

####
# import the environment
####
Import('env variant_dir')
env = env.Clone()
env.Append(CPPDEFINES=["APPLICATION_XERCES"], CPPPATH=variant_dir)

####
# build sources
####
srcs = map(lambda x,bd=variant_dir: '%s/%s' % (bd,x), glob.glob("*.cpp"))
srcs = env.Moc(env.Uic("%s/DynamicColormap.ui" % variant_dir)) + srcs
objs = env.SharedObject(srcs)

####
# build the plug-in library and set up an alias to wase building it later
####
lib = env.SharedLibrary('%s/PlugInSamplerQt' % variant_dir,objs)
libInstall = env.Install(env["PLUGINDIR"], lib)
env.Alias('PlugInSamplerQt', libInstall)

####
# return the plug-in library
####
Return("libInstall")
